### ISSUE TITLE
An array of Regexes returns array of empty objects

### ISSUE THREAD

**Issue by demisx** [mozilla/node-convict#103]
Using v1.0.2

I am defining an array of regexes like this:

``` js
var convict = require('convict');

var config = convict({
  authorizedReferrers: {
    doc: 'Authorized HTTP referrers that can access this web service',
    format: Array,
    default: [
      /^http:\/\/www.domain1.com\/.*/,
      /^http:\/\/www.domain2.com\/.*/
    ],
    env: 'DATA_API_AUTHORIZED_REFERRERS'
  }
});

module.exports = config;
```

Later, in another file trying to retrieve this array of regexes, I get an array of empty objects instead of regexes:

``` js
config.get('authorizedReferrers') // <-- Returns empty an array of empty objects [ {}, {} ]
```

Works fine if I replace regexes with strings. Am I missing something?

**Comment by gurpreetatwal** [comment]
I'm guessing the `JSON.parse(JSON.stringify())`  is there to allow for an easy deep clone, but it should be replaced with an actual deep clone function

**Comment by madarche** [comment]
Thanks @gurpreetatwal . I have just tested and the reported issue is indeed fixed in the current new release.
