### ISSUE TITLE
Dynamic schema

### ISSUE THREAD

**Issue by Sk1Zy** [mozilla/node-convict#106]
I'm writing a small framework that will make use of plugins. I want plugins to be able to add to the config schema when they are loaded.

However before the plugins load i need to load the config so i can start up the server. Is there any way for me to add to the schema dynamically after it has been loaded? The only way i can see to do it  is by storing the schema object, adding to it and then reload the whole schema after each plugin is loaded.

Is there any other way?

**Comment by madarche** [comment]
Hello @Sk1Zy. `convict` has not been designed with dynamic schema in mind. Adding schema dynamic reload would make `convict` more complicated. What you are suggesting (instantiating a new `convict` object every time the schema object changes) seems to be the way to go and should keep your code clean.

**Comment by Sk1Zy** [comment]
Thank you for the response @madarche
