### ISSUE TITLE
What is the meaning of the `rv` variable?

### ISSUE THREAD

**Issue by madarche** [mozilla/node-convict#115]
What is the meaning of the `rv` variable in [convict.js code](https://github.com/mozilla/node-convict/blob/2574b37c42067f77b253c223208624f1471904eb/lib/convict.js#L319)?

Could we rename `rv` into something more meaningful?

This `rv` name has always puzzled me and makes me uncomfortable with one contribution I would like to make.

@lloyd, being the author of this line, could you help on this please? Thank you!

**Comment by madarche** [comment]
I know it's a detail, so sorry again for that.

@zaach any idea on this please?

**Comment by zaach** [comment]
My guess is "return value". Feel free to rename/refactor it.

**Comment by madarche** [comment]
Thanks @zaach! OK, so since the actual name is quiet meaningless at least a rename can be done.
