### ISSUE TITLE
Coercion issue (TypeError) with convict.load and convict.loadFile

### ISSUE THREAD

**Issue by enten** [mozilla/node-convict#126]
node-convict @ 1.1.2
### Error thrown

```
TypeError: Cannot read property 'get' of undefined
    at /home/steven/code/restau/config.js:11:72
    at String.replace (native)
    at Object.convict.addFormat.coerce [as placeholder] (/home/steven/code/restau/config.js:11:16)
    at coerce (/home/steven/code/restau/node_modules/convict/lib/convict.js:273:32)
    at /home/steven/code/restau/node_modules/convict/lib/convict.js:238:15
    at Array.forEach (native)
    at overlay (/home/steven/code/restau/node_modules/convict/lib/convict.js:235:21)
    at Object.rv.load (/home/steven/code/restau/node_modules/convict/lib/convict.js:378:7)
    at Object.<anonymous> (/home/steven/code/restau/config.js:42:6)
    at Module._compile (module.js:398:26)
```
### Cause
- [`coerce` function](https://github.com/mozilla/node-convict/blob/a22e05f218e2ca96067efb6f28e0a63a887096fb/lib/convict.js#L267) requires a convict instance in the fourth param
- [`overlay` function](https://github.com/mozilla/node-convict/blob/a22e05f218e2ca96067efb6f28e0a63a887096fb/lib/convict.js#L234) call `coerce` without convict instance because `overylay` has no reference to one
- [`load`](https://github.com/mozilla/node-convict/blob/a22e05f218e2ca96067efb6f28e0a63a887096fb/lib/convict.js#L377) and [`loadFile`](https://github.com/mozilla/node-convict/blob/a22e05f218e2ca96067efb6f28e0a63a887096fb/lib/convict.js#L384) functions don't give the convict instance reference to `overlay` ([378](https://github.com/mozilla/node-convict/blob/a22e05f218e2ca96067efb6f28e0a63a887096fb/lib/convict.js#L378) and [388](https://github.com/mozilla/node-convict/blob/a22e05f218e2ca96067efb6f28e0a63a887096fb/lib/convict.js#L388))
### How to reproduce it

``` javascript
'use strict';

const convict = require('convict');

convict.addFormat({
  name: "placeholder",
  validate: function(val) {
    /* validate proper path here */
  },
  coerce: function(val, config) {
    return val.replace(/\$\{([\w\.]+)}/g, function(v,m) { return config.get(m); }); /* line 11 */
  }
});

var conf = convict({
  env: {
    format: ['production', 'development'],
    default: 'development',
    env: 'NODE_ENV',
    doc: 'The environment that we\'re running in.'
  },
  configPath: {
    format: 'placeholder',
    default: '/path/to/config',
    doc: 'Path to configuration files.'
  },
  config: {
    format: 'placeholder',
    default: '${configPath}/${env}.json',
    doc: 'Path to configuration file.'
  }
});

conf.get('config');
// return "/path/to/config/development.json"

conf.set('config', '${configPath}/foo.json');
conf.get('config');
// return "/path/to/config/foo.json"

conf.load({ config: '${configPath}/bar.json' }); /* line 42 */
// throw "TypeError: Cannot read property 'get' of undefined"
```
### How to fix it

Transport the convict instance reference from `load` and `loadFile` to `coerce` with adding it in `overlay` last param.
### Pull request

I will make a PR in few minutes to fix that issue.

**Comment by enten** [comment]
Fix available in PR #127.
[All unit tests passed](https://travis-ci.org/mozilla/node-convict/builds/112406974)

With this fix, the upper code (to reproduce the issue) works and the final value returns by `conf.get('config')` is `/path/to/config/bar.json`.

**What do you think about this issue and this fix?**
Is it ready to be merged?

**Comment by gurpreetatwal** [comment]
@madarche I believe this issue should be closed, the corresponding PR was closed

[reasoning](https://github.com/mozilla/node-convict/pull/127#issuecomment-267836903)

**Comment by madarche** [comment]
You are right. Thanks a lot again @gurpreetatwal.
