### ISSUE TITLE
Explicitly loading config gets clobbered by environment variables

### ISSUE THREAD

**Issue by myndzi** [mozilla/node-convict#130]
Because of: https://github.com/mozilla/node-convict/blob/master/lib/convict.js#L379-L381

This behavior is counterintuitive, since if you execute `conf.load(some object)`, the result does not necessarily include the values you supplied. There is no other method to allow you to load an object literal or multiple keys in, with precedence over environment vars / arguments. I'm not sure what the desired solution would be, but there should be some way to do this without having to loop and use `.set`...

**Comment by madarche** [comment]
I'm closing this ticket for now. But you can reopen it and if so, please could you provide a use case and a working example? I think I understand what you mean, but I don't think there is any problem.
