### ISSUE TITLE
Doesn't work when no default specified

### ISSUE THREAD

**Issue by rofrol** [mozilla/node-convict#131]
I use convict only for validation and use env variables, but I can't create schema without default values.

**Comment by madarche** [comment]
Have you tried to use `null` default values?

**Comment by rofrol** [comment]
I've used undefined and it works, but it wasn't obvious that I have to specify default value https://github.com/rofrol/scrape/blob/49316155e37b322ba47e00f197a0427777e1dc5c/config.js

**Comment by madarche** [comment]
If you want to improve the doc you're welcome :-)

**Comment by rofrol** [comment]
Of course I can improve doc, though value more convention over configuration and this maybe better for newcomers, don't you think?

**Comment by madarche** [comment]
@rofrol sorry I don't understand what you mean. Do you mean that it would be better to let the doc be improved by newcomers?

There is this part of a test that seems to check exactly the subject of your question: https://github.com/mozilla/node-convict/blob/master/test/format-tests.js#L110-L113 so it seems safe to document this "optional" use case.

**Comment by rofrol** [comment]
No, I mean that saner defaults would be to let convict work without specifying defaults. Especially when I don't what any defaults:

> Express already alters your ENV variables, in defaulting to 'development' it is leaving a giant gaping hole for mistakenly left in development code to run against your production database. I used the example, that I actually caught, of a call to sequelize.sync({force: true}) that a junior dev was using in a model to quickly reset the database while working on a bulk insert method.
> The actual correct answer here, as mentioned by a few people is to throw on the missing env variable, and bail out of the application. It should be the default setting.
https://www.reddit.com/r/node/comments/3e9f2f/processenvnode_env_undefined_should_it_default_to/ctd3w07

**Comment by madarche** [comment]
@rofrol OK to have saner defaults. Could you work on a PR for this please? Thank you!
