### ISSUE TITLE
Encrypting sensitive config

### ISSUE THREAD

**Issue by damnhipster** [mozilla/node-convict#140]
Projects I've worked on in the past needed their config files checked into a repository so config could be shared with other maintainers. I've come across this scenario again but I'm using node-convict.

To protect sensitive data from prying eyes, I'm suggesting we add a way to allow encrypted config to be passed along via config files, and supply a way for clients to decrypt the data via node-convict.

We can add a new setting into the schema:
```javascript
var schema = {
  heroku: {
    access_key: {
      doc: "Access key to deploy to heroku",
      format: String,
      secret: "$6$t4bgez45$Zf3J3U6ow3kAKBFMsEAGw.EG8v5MMtl6M39j4t2Lz2U7gNMhthJEGg65jxCgfJbwMoWSW4IjfYoCXXY5nXDeI."
    }
  }
}
```

```json
{
  "heroku": {
    "access_key":  "$6$s7o7ttha$IVFh2SKh5vKz"
  }
}
```

Where the secret is some key provided by the user passed through an encryption algorithm hosted as a service for node-convict (such as RSA, signed by a node-convict private key).

I'm not sure how node-convict could go about decrypting the data though, need suggestions for that bit.

We may want to only keep one secret per schema, but the above let's you put a different secret per setting.

What does everyone think? Is it possible to do this via the `format` property, by passing in some custom function? Is it worth making this a standard feature?

**Comment by madarche** [comment]
I do understand the use case. It feels a bit too specific for convict but can still be considered. So it's not a definitive "No". Ideally this should be supported by some kind of plugin. But more simply maybe a custom Formater with a custom `coerce` method could do the job see #110. Could you try that?

**Comment by damnhipster** [comment]
I don't think this would work because there would be no way for node-convict to decrypt the data without making a call to an external service to decrypt securely. That sounds out of scope for this work.

**Comment by et** [comment]
Hi from the future. @damnhipster would [git-crypt](https://github.com/AGWA/git-crypt) work for your use case.
