### ISSUE TITLE
[WIP]: Native support for "semver" format

### ISSUE THREAD

**Issue by LongLiveCHIEF** [mozilla/node-convict#144]
I often find that I need to specify versioning as a format.  I'm working on a format that would add `semver` to my current project, and I will create a PR to add this as a natively supported format for convict when I'm done.

**Comment by madarche** [comment]
Hello. Nice idea to contribute that and thank you for taking your time to share. Still, we won't add everybody's formats (think [Node aesthetic](http://substack.net/node_aesthetic)). So I would rather see this:

1. Document how to create your proposed format (and while you're at it you could also document how to use URL format as in #93) in a dedicated new document (let it be in a `doc/custom-formats.md` file)
2. Develop a convict format plugin framework to register additional formats that convict users could share

The first can be done easily, while the 2nd will need more take more time and effort.

Thank you again

**Comment by LongLiveCHIEF** [comment]
Actually, I realized this same concern already, and I started work on the second item yesterday.  I have a branch with that work in progress already.

So far, I've focused on isolating the format based code and api's into their own module within the convict codebase. This means that convict would have more than just the single `convict.js` source file, and I wanted to ensure that the project team was ok with this change before I spent too much time walking that path.

I'm almost done with the format itself, but the easiest way to do this was to include a new dependency ([semver](https://npmjs.org/semver)), which is what got me started down the plugin path.

The other alternative I'm exploring is creating a `version` format spec instead, that would basically validate if `'latest' || 'int'` is true.  That would be a few lines of code, and wouldn't require any deps, and might be useful enough for the core convict module itself.

**Comment by LongLiveCHIEF** [comment]
Another note re: plugins... this module is written very pure, so it basically supports plugins already, as long as you export a valid schema.

There *could* be a something in convict' s api  that would validates a plugin's schema, but the simplest thing I'm seeing right now is that "plugins" could just be a recommended nomeclature and some documentation.

**Comment by madarche** [comment]
Yes, actually `Convict#addFormat` is already a plugin framework!

**Comment by LongLiveCHIEF** [comment]
This was super simple to accomplish, I'm wrapping my findings into a module that you can pass to `convict.addFormat(require('convict-semver'))`, and will publish shortly.
