### ISSUE TITLE
Schema file validation for built-in types fails silently 

### ISSUE THREAD

**Issue by damnhipster** [mozilla/node-convict#145]
I have a format property for a setting which is set to validate against the javascript built-in type `String`.

It doesn't seem to work. I'm expecting some validation error to be thrown, but 
```
conf.validate({strict: true})
conf.get('aws.s3.bucket')
```
just fails silently, and returns back the schema. I'm using v1.2.0 which contains the feature allowing schema files to have built-in type validation.

Here's the full code:

```javascript
var convict = require('convict');
var schema = base.require('../config/schema.json');

var conf = convict(schema);
conf.loadFile('config/' + conf.get('env') + '.json');

conf.validate({strict: true});

conf.get('aws.s3.bucket');
```

```json
//config/schema.json

{
  "env": {
    "doc": "The applicaton environment.",
    "format": ["production", "development", "test", "local"],
    "default": "local",
    "env": "NODE_ENV"
  },
  "aws": {
    "s3": {
      "bucket": {
        "doc": "Name of S3 bucket to publish to",
        "env": "AWS_S3_BUCKET",
        "format": "String"
      }
}
```

Command run: `AWS_S3_BUCKET=some-bucket node server.js`

**Comment by pdehaan** [comment]
@damnhipster Why were you expecting a validation error? You specified a format of "String" and you're passing a string from the command line.

When I `console.log()` the `conf.get('aws.s3.bucket')` I get the following:

```js
{ doc: 'Name of S3 bucket to publish to',
  env: 'AWS_S3_BUCKET',
  format: 'String' }
```

But when I modify the `config/schema.json` and add a default value, I get back the expected bucket name:

```json
  "aws": {
    "s3": {
      "bucket": {
        "doc": "Name of S3 bucket to publish to",
        "env": "AWS_S3_BUCKET",
        "format": "String",
        "default": null
      }
    }
  }
```

Which gives me the following:

```sh
$ AWS_S3_BUCKET=some-bucket node server.js

some-bucket
```

**Comment by damnhipster** [comment]
Yes, I just came to the same conclusion, it was the fact that I hadn't put a default.
