### ISSUE TITLE
In README give example how to use convict with a JSON/JSON5 schema file

### ISSUE THREAD

**Issue by madarche** [mozilla/node-convict#147]
At the moment it's only written "convict() takes a schema object or a path to a schema file and returns a convict configuration object", but no actual example is given, which leads newcomers to think that convict can only use a schema object.

**Comment by LongLiveCHIEF** [comment]
Convict only *does* use a schema object.  All the remaining examples on the page show how that schema is constructed, manipulated, and supported.

**Comment by madarche** [comment]
It's possible to use a JSON/JSON5 schema file, cf. https://github.com/mozilla/node-convict/blob/master/test/schema-tests.js#L17
