### ISSUE TITLE
Replace optimist which is deprecated

### ISSUE THREAD

**Issue by madarche** [mozilla/node-convict#149]
Replace optimist, which is deprecated (as noted in #125, thanks @sykaeh), by another module, maybe [minimist](https://www.npmjs.com/package/minimist). I'm not in favor of `commander` which does too many things for the small needs of convict.

**Comment by LongLiveCHIEF** [comment]
Actually, my use, and subsequent dissatisfaction with `commander` and then `yargs` is what caused me to start using `convict` to begin with.  I'll take this as a WIP if no one else has started working on it yet.  I've gotten halfway there already when I started #144

**Comment by madarche** [comment]
I haven't started working on this issue. So please do if you can. Thanks!
