### ISSUE TITLE
Contributor Request

### ISSUE THREAD

**Issue by LongLiveCHIEF** [mozilla/node-convict#150]
If possible, I'd like to be made into an external contributor for convict.  [We](https://github.com/StateFarmIns) use it heavily, and I'd like to:
- help maintain communication with users that open issues
- ensure docs are doing what they need to do
- assist in keeping the package up to date
- responding to and collaborating on sensible feature requests
- assisting in active development of any agreed upon roadmap items

Thanks!

**Comment by LongLiveCHIEF** [comment]
Examples of my "maintainer/collaborator" type of actions mentioned above:

- https://github.com/mozilla/node-convict/pull/132
- https://github.com/mozilla/node-convict/issues/128
- https://github.com/mozilla/node-convict/issues/133

/cc @madarche @rfk @vladikoff

**Comment by madarche** [comment]
Hello @LongLiveCHIEF  Thanks for your interest and help proposal which is a real good news. I encourage you to make just one or two more PR and I'm personally all for it. But I have no power to make you such. It's @rfk @vladikoff

**Comment by rfk** [comment]
FWIW I'm happy to support this based on a 👍 from @madarche; @LongLiveCHIEF thanks for your contributions so far!

**Comment by madarche** [comment]
I'm closing this ticket for now.
