### ISSUE TITLE
Browserify and varify

### ISSUE THREAD

**Issue by mlucool** [mozilla/node-convict#153]
Hi,

The assumption that a user will use browserify (over webpack or nothing) seems too strong. I suggest moving varify to an [optional dependency](https://docs.npmjs.com/files/package.json#optionaldependencies). This will reduce install size by 2MB. For those who leave node default settings as it, it will continue to install varify as optional dependencies are installed but won't break if they cannot be installed.

**Comment by madarche** [comment]
I've moved `varify` to `optionalDependencies`, but the module still appears in the `npm-shrinkwrap.json` file. So this modification produces no effect in the end unless the `npm-shrinkwrap.json` generation can be changed to take this change into account.

Nevertheless I'm closing this issue. Feel free to open it again if you have more clues.

**Comment by mlucool** [comment]
Thanks for the change. It seems like the shrinkwrap issue is on the roadmap to be fixed :/
See: https://github.com/npm/npm/issues/2679
See: https://github.com/npm/npm/wiki/Roadmap-area-of-focus%3A-bundling

**Comment by madarche** [comment]
Thanks a lot @mlucool for the references!
