### ISSUE TITLE
suggestion : allow import from key:value based on param

### ISSUE THREAD

**Issue by id0Sch** [mozilla/node-convict#159]
hi,
my team is split into devops and devs 
devops are incharge of setting the necessary values for my apps' config and i'm responsible for the app.
we have some integration issues when i play around with the config structure (server.port => httpserver.port , etc...)

our solution right now is to load a key:value mapping file from either dynamo / file that looks like

```
PORT : 1337,
SERVER_URL : 'WWW.EXAMPLE.COM'
```

and i parse it into the config by doing this

```
for (let key of Object.keys(config)) {
        process.env[key] = config[key];
    }
```

do you think it would be useful to add an 'identifier' or 'key' property that will allow me to achieve this functionality?
if i wasn't clear (might be the case), it allows the config provider to be unaware of the apps config structure and just provide the details needed.

thanks!

**Comment by id0Sch** [comment]
?

**Comment by madarche** [comment]
Hello @id0Sch,
First sorry for the delay.
The schema of the config file is the API that everyone (the devops team and the dev team) has to follow: If you want to change this API, you are then faced with the same problems that everyone else has when changing their API :-\

So first you might still support the old schema keys while providing new ones, and at some date (when you are confident with your new names/standards/conventions) you might remove support for the old schema keys. At this time your devops team will be securely prompted to change the old keys thanks to the strict validation that convict optionally provides:
```javascript
conf.validate({strict: true})
```

Or you can deal with a mapping step as it seems you are suggesting.

I hope this answer will help you.

**Comment by madarche** [comment]
#182 has introduced the possibility to simply warn during validation. This is very useful when doing API transition.
