### ISSUE TITLE
ws:// protocol not supported

### ISSUE THREAD

**Issue by warent** [mozilla/node-convict#170]
AngularClass/angular-websocket requires a url to use the `ws://` protocol. If I try to define this via `format: 'url'` it spews.

**Comment by pdehaan** [comment]
Ref: https://github.com/mozilla/node-convict/issues/93

I think you can just use a custom `validator.isURL()` format and allow `ws://` and `wss://` protocols. Maybe something like @madarche's https://github.com/mozilla/node-convict/issues/93#issuecomment-173534732:

```js
const validator = require('validator');
convict.addFormat({
    name: 'ws-uri',
    validate: function(val) {
        if (!validator.isURL(val, {protocols: ['ws', 'wss']})) {
            throw new Error('must be a web socket URI');
        }
    }
});

var conf = convict({
    uri: {
        doc: 'web socket URI',
        format: 'ws-uri',
        default: ''
    }
});
conf.load({uri: 'ws://localhost:27017/blah'});
conf.validate({strict: true});
```
