### ISSUE TITLE
Coerce only accounts for default values

### ISSUE THREAD

**Issue by tatemz** [mozilla/node-convict#172]
Looking at the code below, while using the suggested "placeholder" format from the README, the placeholder functionality does not take into account the _loaded values_. Is there a way to recalculate the "placeholder" values upon calling `.get()`

The following command is being run to execute the following snippet: `NODE_ENV=prod node index.js`

```javascript
convict.addFormat({
  name: "placeholder",
  validate: function(val) {
  },
  coerce: function(val, config) {
    return val.replace(/\$\{([\w\.]+)}/g, function(v,m) { return config.get(m) })
  }
});

var conf = convict({
  env: {
    doc: "The applicaton environment",
    format: ["dev", "prod"],
    default: "dev",
    env: "NODE_ENV",
    arg: "env",
  },
  configFile: {
    doc: "Configuration file",
    format: "placeholder",
    default: "${env}.json",
  },
});


console.log(conf.get("env")); // "prod"
console.log(conf.get("configFile")); // "dev.json"

conf.loadFile(conf.get("configFile"));

console.log(conf.get("env")); // "prod"
console.log(conf.get("configFile")); // "dev.json"
```

**Comment by tatemz** [comment]
@madarche Any thoughts? I hate to pester, but I have tried to resolve this on my own to no avail :-(

I'll submit a PR if I am able to debug deeper, but any collaboration is much appreciated.

**Comment by madarche** [comment]
@tatemz: I'll try again soon.

**Comment by madarche** [comment]
@tatemz I couldn't make it work either :-( and even the placeholder example in the README doesn't work with `set` :-( (instead of the `loadFile` that is your current problem).

From Convict's README, the coercion usecase is to coerce environmental variables from strings to their proper types when importing them. This is a needed and thus legitimate usecase for a configuration handler. And since the actual Convict's code is already too complicated in the coercion and overlay areas I'm sorry but no other usecases will be supported.

**Comment by tatemz** [comment]
@madarche - That's reasonable. I'll just have to do it the verbose way and concatenate some variables. Thanks for looking into it! 💯

**Comment by tatemz** [comment]
@madarche 

UPDATE:

Here is how I am accomplishing my goal with the aforementioned example:
```
convict.addFormat({
  name: "placeholder",
  validate: function(val) {
  },
  coerce: function(val, config) {
    return val.replace(/\$\{([\w\.]+)}/g, function(v,m) { return config.get(m) })
  }
});

var conf = convict({
  env: {
    doc: "The applicaton environment",
    format: ["dev", "prod"],
    default: "dev",
    env: "NODE_ENV",
    arg: "env",
  },
  configFile: {
    doc: "Configuration file",
    format: "placeholder",
    default: "${env}.json",
  },
}).load({});

conf.getVar = function(property) {
  var self = this;
  var val = self.get(property);
  
  if ( typeof val === "string" ){
    return val.replace(/\$\{([\w\.]+)}/g, function(v,m) { return self.get(m) });
  }

  return val;
}

console.log(conf.getVar("env")); // "prod"
console.log(conf.getVar("configFile")); // "dev.json"

conf.loadFile(conf.getVar("configFile"));

console.log(conf.getVar("env")); // "prod"
console.log(conf.getVar("configFile")); // "prod.json"
```

**Comment by madarche** [comment]
@tatemz thanks for the heads up! And glad that you have a solution.

FYI for the future I would prefer that convict has a new explicit format for such a usecase: it could be a format named *computed* that would have its value computed from other properties. That way it wont' mess with the coercion code and this code would be straightforward to understand and maintain.

Cheers

**Comment by tatemz** [comment]
@madarche - Suggestion, rather than adding a "format", perhaps it would best that the format contain one additional method alongside it's siblings... for instance:

```
convict.addFormat({
  name: "myFormat",
  validate: function(val) {
  },
  coerce: function(val, config) {
  },
  compute: function(val, config, optionalParams) {
  }
});
```

**Comment by madarche** [comment]
@tatemz what are the advantages of an additional *compute method* over a new *computed format*? Could you elaborate please? Thanks

**Comment by tatemz** [comment]
@madarche I don't know enough about the code base nor enough about the potential application to know if adding a _compute method_ is more advantageous than a _computed format_.

I consider the word "format" nearly synonymous with a Javascript "type" due to the fact that (per your documentation) for each official "type", there is a corresponding "format". Thus, my intuition says that, as a user, I should be able to **both** compute and coerce a variable, regardless of its type. 

To clarify, my current understanding is that _coerce_ happens only upon initialization (as proved by the [original comment](https://github.com/mozilla/node-convict/issues/172#issue-194620726)) and serves to strictly normalize a default variable.

My understanding of a `compute` method is that it would exist to be a kind of "getter" that could take the _coerced_ input and output something new altogether. For instance, the format could take an `int` as an input, but output a `string` like `"Your number is 1"`

Perhaps I am off-base and missing some obvious hole in my understanding, and maybe the original issue could be resolved if using `config.get()` re-ran `coerce()` with most updated variables.

Hopefully, that was all clear as mud 🤓 😁
