### ISSUE TITLE
npm install convict ignores registry settings

### ISSUE THREAD

**Issue by sebradloff** [mozilla/node-convict#180]
We are trying to install convict in a proxy environment. 
We have our .npmrc has registry settings like so:
`
registry = "http://artifactory/"
@npm:registry = "http://artifactory/"
`

For some reason the following packages are not being resolved through artifactory but are trying to resolve to the npmjs.org.
`
31-Jan-2017 13:54:04	npm ERR! fetch failed https://registry.npmjs.org/lodash.clonedeep/-/lodash.clonedeep-4.5.0.tgz
31-Jan-2017 13:54:04	npm WARN retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
31-Jan-2017 13:54:04	npm ERR! fetch failed https://registry.npmjs.org/json5/-/json5-0.5.1.tgz
31-Jan-2017 13:54:04	npm WARN retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
31-Jan-2017 13:54:04	npm ERR! fetch failed https://registry.npmjs.org/minimist/-/minimist-1.2.0.tgz
31-Jan-2017 13:54:04	npm WARN retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
31-Jan-2017 13:54:04	npm ERR! fetch failed https://registry.npmjs.org/moment/-/moment-2.17.1.tgz
31-Jan-2017 13:54:04	npm WARN retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
31-Jan-2017 13:54:04	npm ERR! fetch failed https://registry.npmjs.org/varify/-/varify-0.1.1.tgz
31-Jan-2017 13:54:04	npm WARN retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
31-Jan-2017 13:54:04	npm ERR! fetch failed https://registry.npmjs.org/validator/-/validator-6.2.0.tgz
`
We have in fact confirmed that these logs do come from installing convict specifically by logging into our environment servers and running `npm install convict`, while other packages resolve through artifactory.

Is there a strange postinstall step that convict is trying to do or a way to force convict to resolve those dependencies from artifactory?

**Comment by madarche** [comment]
Hello @sebradloff . Tanks for your interest in Convict. The (`package.json`)[https://github.com/mozilla/node-convict/blob/master/package.json] file doesn't reference any registry, but the (`npm-shrinkwrap.json`)[https://github.com/mozilla/node-convict/blob/master/npm-shrinkwrap.json] file does! Check its content. If you can find a way to generate an `npm-shrinkwrap.json` file compatible with any registry/proxy please let us know!

**Comment by sebradloff** [comment]
Thanks @madarche for the response! We might end up looking into cloning down convict and editing the shrinkwrapped registry. By any chance do you know if convict can be used client side, using webpack and not gulp && browserify?

**Comment by madarche** [comment]
@sebradloff it used to work, but it never has been a goal for Convict, see #47
