### ISSUE TITLE
Option for loadFile to run optimistically but fail quietly.

### ISSUE THREAD

**Issue by bchristie** [mozilla/node-convict#185]
Could there be an option to specify a silent failure if `.loadFile` is unable to find the file? Currently an error is thrown:

> Error: ENOENT: no such file or directory, open '/path/to/development.json'

The purpose is to optimistically load `./${conf.get('env')}.json`, but not require it. Currently an `fs.access` check is required first. Thoughts?

**Comment by madarche** [comment]
Hello @bchristie: I think I understand what your idea is, but when a developer calls the `loadFile` method they want to have the action done or failed with an error. This is the paradigm used everywhere. What you could do is, in your own code, to test the existence of your file and call `loadFile` or not upon it.
