### ISSUE TITLE
_instance -- Should this be used?

### ISSUE THREAD

**Issue by bchristie** [mozilla/node-convict#186]
I was introducing convict into an existing app, but given the API (`.get`/`.set`) I looked for something that would allow me to migrate in the least invasive fashion. I came across `_instance` and hesitate to use it given it's internal naming convention.

So, that said, is `_instance` there for the taking or (s/c)hould a new API be created to expose similar functionality? Ideally I'm looking for something to closely resembling a "traditional" JSO until instances have been altered to leverage `.get`. I'm also imagining I'm not the only one looking for a `toJSO()` call for this (or other) purpose.

**Comment by madarche** [comment]
@bchristie I think you mean that it would have been great that Convict could just give direct access to its properties without having to resort to the `get` and `set` methods. I would have love that too when I switched to Convict :-) So you're clearly not the only one.

One thing is for sure, you should not rely on accessing a variable clearly marked internal, such as `instance`.

That said, I think what you are looking for should be the `getProperties` method. Go for it!
