### ISSUE TITLE
Feature request: ability to mark sensitive values for masking in toString()

### ISSUE THREAD

**Issue by elyscape** [mozilla/node-convict#187]
It can be useful, when an application starts, to print out what it has determined the configuration to be; this allows the user to determine whether their issue is with configuration or elsewhere. To that end, it would be nice if convict provided a way to flag certain values as sensitive and have them masked by `toString()`. To illustrate, consider this code sample:
```javascript
'use strict';
const convict = require('convict');

let config = convict({
  secretKey: {
    default: null,
    env: 'SECRET_KEY',
    sensitive: true
  },
  notSecret: {
    default: 'public'
  }
});

console.log("config.get('secretKey'):");
console.log(config.get('secretKey'));
console.log();
console.log("config.get('notSecret'):");
console.log(config.get('notSecret'));
console.log();
console.log('config.toString():');
console.log(config.toString());
```
Currently, this is what happens when it's executed:
```shellsession
scapeless:convictmask elyscape$ SECRET_KEY=this-is-a-secret node sensitive-demo.js 
config.get('secretKey'):
this-is-a-secret

config.get('notSecret'):
public

config.toString():
{
  "secretKey": "this-is-a-secret",
  "notSecret": "public"
}
```
What I am proposing is that, if a field has `sensitive: true` set on it, something like this happens instead:
```shellsession
scapeless:convictmask elyscape$ SECRET_KEY=this-is-a-secret node sensitive-demo.js 
config.get('secretKey'):
this-is-a-secret

config.get('notSecret'):
public

config.toString():
{
  "secretKey": xxx,
  "notSecret": "public"
}
```
`config.get('secretKey')` still returns the actual value, but when it's output through `config.toString()`, the actual value is masked and safe for logging.

Adding this behavior to `config.toString()` would, of course cause breakage if anybody is for some reason relying on that to be valid JSON, so it might make more sense to add another function (`config.toSafeString()` or something) that masks sensitive fields. That being said, doing that means that the following would then be unmasked, which while not a huge deal is somewhat less convenient than if it were masked:
```javascript
console.log(`The config is: ${conf}`); // ${conf} is translated internally to conf.toString()
```

**Comment by elyscape** [comment]
This might also be a good idea to apply to the error messages produced by validation failures on sensitive values. Currently, the error string prints the value provided:
```javascript
'use strict';
const convict = require('convict');

let config = convict({
  secretNum: {
    format: 'nat',
    default: null,
    env: 'SECRET_NUM',
    sensitive: true
  },
  publicNum: {
    format: 'nat',
    default: null,
    env: 'PUBLIC_NUM'
  }
});

try {
  config.validate();
} catch (err) {
  console.error(err.message);
  console.error();
}

console.log("config.get('secretNum'):");
console.log(config.get('secretNum'));
console.log();
console.log("config.get('publicNum'):");
console.log(config.get('publicNum'));
console.log();
console.log('config.toString():');
console.log(config.toString());
```
```shellsession
scapeless:convictmask elyscape$ SECRET_NUM=-11 PUBLIC_NUM=-12 node sensitive-test.js 
secretNum: must be a positive integer: value was -11
publicNum: must be a positive integer: value was -12

config.get('secretNum'):
-11

config.get('publicNum'):
-12

config.toString():
{
  "secretNum": -11,
  "publicNum": -12
}
```
With masking:
```shellsession
scapeless:convictmask elyscape$ SECRET_NUM=-11 PUBLIC_NUM=-12 node sensitive-test.js 
secretNum: must be a positive integer
publicNum: must be a positive integer: value was -12

config.get('secretNum'):
-11

config.get('publicNum'):
-12

config.toString():
{
  "secretNum": xxx,
  "publicNum": -12
}
```

**Comment by madarche** [comment]
Hello @elyscape. I'm totally OK for this (very thorough and justified) feature request.

To be more precise:

* OK for a `sensitive: true` field property
* OK for altering the `toString()` method
* And there's no compatibility issue since nobody is supposed to parse the output of the `toString()` method. There's a `getProperties()` method providing a JSON export

You're more than welcome to work on a corresponding PR

**Comment by elyscape** [comment]
I'll take a stab at it shortly.
