### ISSUE TITLE
How should validate() handle missing nested values?

### ISSUE THREAD

**Issue by elyscape** [mozilla/node-convict#193]
While working on #192, I discovered an interesting bug. Specifically, if one sets a field's parent to some value, via `set()`, `load()`, or `loadFile()`, that field vanishes without the rest of convict noticing. Test case:
```javascript
'use strict';
const convict = require('convict');

let config = convict({
  parent: {
    child: {
      default: 'child value',
      format: String
    }
  }
});

config.validate({allowed: 'strict'}); // succeeds

config.get('parent'); // -> {child: 'child value'}
config.get('parent.child'); // -> 'child value'

config.set('parent', 'parentValue');
// Alternative option:
// config.load({parent: 'parentValue'});
// See also config.loadFile()

config.validate({allowed: 'strict'}); // succeeds

config.get('parent'); // -> 'parentValue'
config.get('parent.child'); // throws TypeError: Cannot use 'in' operator to search for 'child' in parentValue
```
This can have problems downstream if, say, a malformed config file nukes a tree that the app is expecting to exist. Other fun results:
```javascript
'use strict';
const convict = require('convict');

let config = convict({
  parent: {
    childOne: {
      default: 'childOne',
      format: String
    },
    childTwo: {
      default: 'childTwo',
      format: String
    }
  }
});

config.get('parent'); // -> {childOne: 'childOne', childTwo: 'childTwo'}

config.set('parent', null);
config.get('parent'); // -> null
config.set('parent.childOne', 'new childOne');
config.get('parent'); // -> {childOne: 'new childOne'}
config.get('parent.childOne'); // -> 'new childOne'
config.get('parent.childTwo'); // throws Error: cannot find configuration param 'parent.childTwo'
config.default('parent.childTwo'); // -> 'childTwo'
config.reset('parent.childTwo');
config.get('parent.childTwo'); // -> 'childTwo'

config.set('parent', 'parentValue');
config.get('parent'); // -> 'parentValue'
config.set('parent.childOne', 'new childOne'); // throws TypeError: Cannot create property 'childOne' on string 'parentValue'
config.default('parent.childOne'); // -> 'childOne'
config.reset('parent.childOne'); // throws throws TypeError: Cannot create property 'childOne' on string 'parentValue'
```
So ultimately my question is this: how should we be handling this case? I would argue that we should probably put checks into `set()`, `load()`, and `loadFile()`, or at least `validate()`. If we put checks into `set()` et al., I'm thinking that they would throw an exception if you try to set a path that either already has an object value or, at a bare minimum, has children in the schema. Meanwhile, `validate()` should ensure that all the properties in the schema exist in the instance.

**Comment by madarche** [comment]
Hello @elyscape. I agree with you on putting checks into `set()`, `load()`, and `loadFile()` that would throw an exception right away in case of bad usage (i.e. on trying to set a non-existing field). As for how to do it, checking if the object has children in the schema is how I would do it. I don't understand when you write "a path that either already has an object value", but I would happily read the code that would do that and I would surely understand better. So should you have time and will to prepare a PR for that, it would be very appreciated!

I prefer to have stricter checks on the schema creation, and thus have cleanly separated schema check on one side and instance check in one other side, than having `validate` trying to cope with a buggy schema later.

**Comment by elyscape** [comment]
Apologies for the delay.

I think we should probably keep the checks (that is to say, the places where we throw exceptions) confined to `validate()`, as they currently are, but we should revamp how `validate()` operates. Right now, it recursively iterates over the keys of `instance` and checks them against the schemes. Instead, it should recursively iterate over the keys of the schema and check the corresponding values in `instance` with an additional step being performed to check for values that aren't in the schema of strict validation is enabled. This could be done by flattening a copy of the instance object and deleting keys as we validate them from the schema. Anything left over would be an extra key.

**Comment by elyscape** [comment]
@madarche I have reworked `validate()` as I described in my previous post. Please take a look at #206 when you have a chance.

**Comment by madarche** [comment]
@elyscape I've read the Convict's comments of the last 2 weeks but had no time to do anything else than just read 😢. I'll have more time to devote to Convict middle of next week.

**Comment by elyscape** [comment]
No worries! Just making sure you saw it.
