### ISSUE TITLE
Typescript types out of date?

### ISSUE THREAD

**Issue by avindra** [mozilla/node-convict#202]
cc @Nemo157 who wrote the original types. 

[The latest types](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/convict/index.d.ts
) in `DefinitelyTyped` for this package appear to be for version `0.6.0`.

Is there any interest in bundling official types and adding the `typings` key to `package.json`, or in updating the third party repo?

**Comment by madarche** [comment]
TypeScript is not used (and won't be) in this project. We prefer to go ES2015 and the next versions of JavaScript.
