### ISSUE TITLE
Remove the npm-shrinkwrap.json file?

### ISSUE THREAD

**Issue by madarche** [mozilla/node-convict#209]
After reading http://blog.npmjs.org/post/161627993435/learn-more-about-npms-lockfiles it seems that we should remove the `npm-shrinkwrap.json` file in Convict.

I like the added value of a npm-shrinkwrap.json file, especially in a "top level" app, but for Convict it's bringing more hindrance (see [CONTRIBUTING](https://github.com/mozilla/node-convict/blob/2f623bb/CONTRIBUTING.md)) than benefit (Convict doesn't rely on especially complex/unstable/weird dependencies).

So I propose to remove the `npm-shrinkwrap.json` file in Convict as part of #201

And we could add `package-lock.json` in the future.

Don't hesitate to comment, especially @pdehaan who proposed the use of shrinkwrap in #63 in the first place. Thanks.

**Comment by pdehaan** [comment]
/cc @jrgm 

The thing about `package-lock.json`, is that I think it'd only apply if people are using npm 5 or later.

**Comment by elyscape** [comment]
@pdehaan That is true. It also only applies when installing at a top level (i.e. you go into the repo and run `npm install`). Still, `npm-shrinkwrap.json` has the potential to cause conflicts for downstream consumers of the library, which I think is something that we should try to avoid.

**Comment by madarche** [comment]
@pdehaan to be explicit: the idea here is to remove the `npm-shrinkwrap.json` for convict@4, and not to add `package-lock.json` nor `yarn.lock`.

Adding `package-lock.json` and `yarn.lock` would be nice for developers, but it's not the point of this ticket. Moreover, even if I follow node@8 and npm@5, I haven't switched to them yet. I'm waiting a bit more.

**Comment by pdehaan** [comment]
Yeah, I'm fine w/ killing npm-shrinkwrap.json in a library if it isn't being helpful. :fire::fire::fire:

I tried searching but couldn't find any solid answers on if shrinkwrap is meant primarily for applications vs modules. I think the best advice I found was to add npm-shrinkwrap.json to the .npmignore file so it doesn't get published to the registry and affect downstream users.

**Comment by madarche** [comment]
Roger @pdehaan

I agree with you that *no npm-shrinkwrap.json in a library* is not really documented anywhere seriously. At this time [the blog post I was referencing](http://blog.npmjs.org/post/161627993435/learn-more-about-npms-lockfiles) has even been unpublished 😕 This article was the most solid piece of literature on the subject I knew, and, still, this was only advices explained as a cartoon, not a concrete case.

But the key fact is, as @elyscape stated: *npm-shrinkwrap.json has the potential to cause conflicts for downstream consumers of the library*.

[Nunjucks](https://github.com/mozilla/nunjucks), a famous Mozilla NPM library, has no npm-shrinkwrap.json file. Since this project is famous, and used in production by Mozilla itself, it can be viewed as a reference on the matter.

Still let's keep an eye on the npm-shrinkwrap.json subject and we can revisit the matter at any time.

Since the matter is fixed for now, I'm going to prepare the convict@4.0.0 release 😄
