### ISSUE TITLE
Precendence order

### ISSUE THREAD

**Issue by hokisimi** [mozilla/node-convict#211]
Precendence order

I try to test Windows, but do not work following.

**When merging configuration values from different sources, Convict follows precedence rules. The order, from lowest to highest, is:

1.Default value
2.File (config.loadFile())
3.Environment variables
4.Command line arguments
5.Set and load calls (config.set() and config.load())**

In Mac computer Precendence order is work well, **But In Windows computer belows order** 

1.Default value
2.File (config.loadFile())
**3.Set and load calls (config.set() and config.load())**
**4.Environment variables**
5.Command line arguments

Set and load calls < Environment variables 

In Windows, Set and load calls is not highes order.

**Comment by williansouzagonc** [comment]
I have same issue as you, but i'm using mac.

**Comment by nathanph** [comment]
The [`load` function](https://github.com/mozilla/node-convict/blob/master/lib/convict.js#L588) suggests that environment variables and arguments always take precedence. This seems like a sane precedence to me but the documentation currently indicates a different precedence and should be updated to reflect what the code is actually doing. If the precedence is going to change, which I don't think should happen, then there should be a major version bump.

```js
/**
 * Loads and merges a JavaScript object into config
 */
load: function(conf) {
  overlay(conf, this._instance, this._schema);
  // environment and arguments always overrides config files
  importEnvironment(rv);
  importArguments(rv);
  return this;
}
```

**Comment by wcho** [comment]
I prefer load has same preference with loadFile. A use case is an encrypted conf file which is decrypted and consumed by convict. It's also ok that loadFile accepts object not only file path.

**Comment by A-312** [comment]
@madarche this issue should be closed

This issue/problem is not reproductible on Windows, I tried : 

```
const config = convict({
  port: {
    format: 'port',
    default: 5000,
    arg: 'port',
    env: 'PORT'
  }
})
```

I got : 

```
λ SET PORT=52                                       
λ echo "%FISH%"                              
"52"                                         
λ node test.js                                
{ port: 52 }
λ node test.js --port 54                      
{ port: 54 }                                 
λ node test.js                                
{ port: 52 }                                 
```

**Comment by zaverden** [comment]
@A-312 your example confirms this issue.

According documentation `config.load(..)` has maximum priority. So, your example should always print `{ port: 58 }`. But you can see that argument and environment have higher priority.

I believe that it is documentation issue, because [this comment](https://github.com/mozilla/node-convict/blob/61e8b9b5b6c89ea905fe8cd962492342ea2b1100/lib/convict.js#L599) shows intention to process arguments and environment with higher priority.

**Comment by A-312** [comment]
I read [a new time](https://github.com/mozilla/node-convict/tree/61e8b9b5b6c89ea905fe8cd962492342ea2b1100#precendence-order), you have right 😕 But, in some cases we should `.load(` to be before or after env and arg. Maybe we should add an new argument to avoid a break change.

Or allow `.set(` to get an object in first parameter : 

 - config.set(name, value)
 - config.set(object)
     - object({name1: 'value', name2: 'value'}

Like that:

1. Default value
2. File (`config.loadFile()`)
3. Load calls (`config.load()`)
4. Environment variables (only used when *env* property is set in schema; can be overridden using the *env* option of the convict function)
5. Command line arguments (only used when *arg* property is set in schema; can be overridden using the *args* option of the convict function)
6. Set calls (`config.set()`)

**Comment by zaverden** [comment]
@A-312 this logic lives [for 8 years already](https://github.com/mozilla/node-convict/blame/61e8b9b5b6c89ea905fe8cd962492342ea2b1100/lib/convict.js#L599). As I see the only problem here is wrong documentation.

In addition I want to say that `config.set()` order is not obvious too. In #314 I have added an example how it can be overridden though it's original order is 5.
