### ISSUE TITLE
Move away from minimist  to yargs-parser

### ISSUE THREAD

**Issue by madarche** [mozilla/node-convict#212]
As written by @elyscape in https://github.com/mozilla/node-convict/pull/199#issuecomment-291310980:

Move away from [minimist](https://www.npmjs.com/package/minimist) for argument parsing, as it appears to be unmaintained, not having received an update since 2015. [yargs-parser](https://www.npmjs.com/package/yargs-parser) seems to be a largely drop-in successor, which also provides the ability to disable auto-conversion of numeric values into numbers.

**Comment by vladikoff** [comment]
👍
