### ISSUE TITLE
Support passing argv and env as arguments to convict function

### ISSUE THREAD

**Issue by mojavelinux** [mozilla/node-convict#222]
The convict function should accept argv and/or env as arguments instead of relying exclusively on the process.argv and process.env globals. The benefit of adding these arguments is that it makes convict unit-test friendly and it allows convict to be used outside of a cli environment (for example, in an IDE).

Here's the current workaround:

```js
function solitaryConvict(schema, argv, env) {
  const oldArgv = process.argv
  const oldEnv = process.env
  const config = convict(schema)
  process.argv = oldArgv
  process.env = oldEnv
  return config
}
```

While this works, it's quite a crude workaround.

**Comment by mojavelinux** [comment]
If this idea is accepted, I'd be happy to do the work of implementing and testing it.

**Comment by madarche** [comment]
I find the idea appealing and that should not complexify the code base. So go ahead please @mojavelinux

**Comment by mojavelinux** [comment]
:clap: 

I'm on it.

**Comment by mojavelinux** [comment]
PR sent!

**Comment by mojavelinux** [comment]
I realized it might be better to define args and env in an options hash instead of as positional parameters.

```js
convict(def, { args: ['--foo', 'foo'], env: { BAR: 'bar' })
```

Would you prefer that signature? If so, I'll make the update.

**Comment by madarche** [comment]
I'm sorry @mojavelinux, reading your PR I realize I may have spoken too fast: at the moment convict can already be used outside a CLI environment, doesn't it? One just has to load an object cf. [config#load(object)](https://github.com/mozilla/node-convict#configloadobject):
```javascript
config.load({
  "env": "test",
  "ip": "127.0.0.1",
  "port": 80
});
```

Couldn't it do the job in your case?

**Comment by mojavelinux** [comment]
No. I consider these two very different things. What I'm proposing is to be able to simulate / control the environment in which convict loads. In other words, I want it to be able to prevent it from using process.argv or process.env at any point (no globals).

If I fully expand the example you gave:

```js
const convict = require('convict')

const config = convict({
  env: {
    format: String,
    default: 'dev',
    arg: 'env'
  },
  ip: {
    format: String,
    default: '127.0.0.1',
    arg: 'ip'
  },
  port: {
    format: Number,
    default: 80,
    arg: 'port'
  }
})

config.load({
  env: 'test',
  ip: '127.0.0.1',
  port: 8080
})

console.log(config.getProperties())
```

then it's still considering the process arguments, as you can see by running:

```js
node convict-test.js --port=8181
```

That's different behavior. I'm looking for complete isolation from the process environment. That's what my PR provides.

**Comment by mojavelinux** [comment]
Btw, I updated the PR to use an options hash instead of positional parameters. That seems more JavaScript like.

**Comment by mojavelinux** [comment]
>  What I'm proposing is to be able to simulate / control the environment in which convict loads. 

I want to clarify why that matters. If I use convict inside of an application which itself has it's own process arguments and environment variables (which may in turn use convict), then using convict internally for a separate concern gets coupled to the process environment of the executing program.

It's also useful in a unit test environment where it's necessary to simulate a process environment (without patching the process global).

**Comment by mojavelinux** [comment]
I want to reiterate why this change is so important. If I use convict within another environment, such as within an IDE, a web framework, or a test suite, convict is looking at the process environment that launched the original process. That has nothing to do with the user input I'm trying to use it to process and validate. This prevents convict from being a reusable / portable library and instead couples it to the process environment.

I've hacked convict to provide this feature. I call it [solitary convict](https://gitlab.com/antora/antora/blob/master/packages/playbook-builder/lib/solitary-convict.js). I'd like it if this workaround was not necessary.
