### ISSUE TITLE
support protocol relative urls

### ISSUE THREAD

**Issue by leftieFriele** [mozilla/node-convict#235]
Currently you have to implement a custom validation function in order to use protocol relative urls when using the url format in convict. The validator package supports the option [allow_protocol_relative_urls](https://github.com/chriso/validator.js/blob/master/src/lib/isURL.js#L15) when validating urls. 

I know similar requests have been closed (#170, #93]. As far as I can tell adding this option to the [validator.isUrl call](https://github.com/mozilla/node-convict/blob/master/lib/convict.js#L69) in convict won't break anything. I'd be happy to create a PR for this if you all think this is a good idea.

**Comment by A-312** [comment]
With my PR #327 , the url format will be a separated paclage see : https://github.com/A-312/node-convict/tree/nodep/packages/convict-validator
