### ISSUE TITLE
Allow functions values

### ISSUE THREAD

**Issue by psirenny** [mozilla/node-convict#25]
If you add a function and try to get it, it returns an empty object:

```
function someFunction () {};
conf.set('path', someFunction);
conf.get('path'); // returns {}
```

**Comment by chiefy** [comment]
:+1: I guess it's not best practice, but I was trying to save a pretty complicated data structure in convict, and it mostly worked except it stripped prototype on custom types. Had me scratching my head.

**Comment by madarche** [comment]
Really node-convict is just about setting/storing values according to a schema. Not about storing functions. What is the usecase?

Or maybe you think a check preventing the setting of a function is missing?

**Comment by chiefy** [comment]
@madarche Yeah, I completely get that, I was misusing convict by storing a large data structure that had arrays of objects etc. It might be useful to throw an exception in this case?

**Comment by madarche** [comment]
Storing functions is not advertized in the doc and is not an error that someone would do by mistake. So I don't think a check on this is necessary.
