### ISSUE TITLE
Cannot invoke an expression whose type lacks a call signature. Type 'typeof convict' has no compatible call signatures.

### ISSUE THREAD

**Issue by burakkarakus** [mozilla/node-convict#252]
I am using TypeScript 2.4.0 with type/convict 4.2. I can't use below code because of the error I stated in the title.

`const conf = convict({
  env: {
    doc: 'The applicaton environment.',
    format: ['production', 'development', 'test'],
    default: 'development',
    env: 'NODE_ENV'
  }});`

`console.log(conf.env.doc);`

Error: doc: must be of type String

**Comment by brikis98** [comment]
@burakkarakus How did you resolve this issue?

**Comment by MacKentoch** [comment]
I guess no answer... 
Maybe removed convict or typescript?
