### ISSUE TITLE
upgrade dependency for hoek

### ISSUE THREAD

**Issue by AutomatedTester** [mozilla/node-convict#258]
There is currently a security warning for the version of hoek used. Please upgrade of if the code isnt used anymore please remove

**Comment by madarche** [comment]
Hello @AutomatedTester. I would love to get rid of [this hoek vulnerability](https://nodesecurity.io/advisories/566) report (for others, do `npm audit` to view the report). But it's present in the `coveralls` NPM package, which we have to its latest version. So there's nothing we can do for it easily right now.

That said, `coveralls` is a *devDependency* that you get only when you develop convict (i.e. `cd node-convict && npm i`). You don't get the `coveralls` package if your applications just have a dependency on convict. Thus your applications should not be impacted at all by the hoek vulnerability. Or please explain how you could be impacted.

**Comment by AutomatedTester** [comment]
@madarche please raise an issue on coveralls and link it to this issue. Currently that vulnerabilty is being reported in the Github security emails generated weekly

**Comment by madarche** [comment]
It should be fixed by the convict@4.3.0 release. Please comment if it's not the case.
