### ISSUE TITLE
Pass the name of the property being assigned to the custom coerce function

### ISSUE THREAD

**Issue by mojavelinux** [mozilla/node-convict#262]
Pass the name of the property to which the value is being prepared to the custom coerce function. This will allow the function to look up the old value and append the new value to it instead of overwriting it. This can be useful for config properties that hold a collection of data.

Example:

```js
coerce: (val, config, name) => { 
  const accum = config.get(name)
  const [k, v] = val.split('=')
  accum[k] = v
  return accum
}
```

The main use case for this is binding the config property to an argument that can be specified multiple times from command-line (e.g., `--attribute key=val`).

**Comment by madarche** [comment]
Hello @mojavelinux. Presently my time is too short to be able to calmly think on issues. So please could you elaborate a bit more: are you requesting approval on a proposed change before submitting the corresponding PR?

**Comment by mojavelinux** [comment]
Correct. I am floating the idea before I commit time to implementing it. This feature would be really useful for the project I'm working on that uses convict for config.

**Comment by madarche** [comment]
OK. I'll take time to think about it and will report back here. Don't hesitate to invite other active users of convict into the discussion!

**Comment by mojavelinux** [comment]
This seems to be a pretty low-impact change because we're simply adding another optional argument for the coerce function to accept.

**Comment by madarche** [comment]
Understood.

**Comment by mojavelinux** [comment]
I sent a PR.

**Comment by A-312** [comment]
I thought coerce function was only to convert value/format not change value depending of dynamic value but this commit is a good hack instead getter (#313). :/
