### ISSUE TITLE
Regular Expression Denial of Service (ReDoS)

### ISSUE THREAD

**Issue by binarymist** [mozilla/node-convict#264]
Details here https://snyk.io/test/npm/convict/4.3.1

**Comment by ddlees** [comment]
It's not a high priority issue for my team but it is showing up in our vulnerability scans. Any help here would keep my security officer quiet 😜

**Comment by binarymist** [comment]
Have added it to my backlog, see who gets there first.

**Comment by madarche** [comment]
Thanks for the heads up!
