### ISSUE TITLE
Defining a configuration property as "required", without providing a default value.

### ISSUE THREAD

**Issue by redking** [mozilla/node-convict#29]
Hey,

Perhaps I'm misreading the docs, but there doesn't appear to be a way to define a configuration property as "required" but without a default value i.e. if the property is not found in the configuration file, then validation will fail. 

This would be especially useful when working with a team of developers. As it stands, a developer could delete a config property without understanding the impact; the application might appear to function, falling back to its default value as defined in the schema, but with consequences further down the line.

If this seems useful, I can try to create a pull request.

**Comment by ash2k** [comment]
- What if in production environment the configuration is taken from the environment variable and it is expected to be injected by the PaaS/etc at runtime and is not known in advance?
- What if using a production value as a default is a bad idea (for some reasons i.e. a DB password)?
- IMHO using `default: null` is not better than making default an optional field. One could argue that invalid default for a required variable is ambiguous and misleading.
- Supporting the case explicitly allows to produce meaningful error messages.
