### ISSUE TITLE
npm install -> 16 high severity vulnerabilities

### ISSUE THREAD

**Issue by A-312** [mozilla/node-convict#293]
```
M:\path\node-convict (fix-add-context -> origin) (convict@5.0.0)
λ npm install
added 329 packages from 693 contributors and audited 888 packages in 7.698s
found 16 high severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
```
Npm audit: https://nodesecurity.io/advisories/1065

Fix: Change the number version in package-lock.json from 4.17.11 to 4.17.15 : 
![image](https://user-images.githubusercontent.com/18501150/61938312-15100180-af91-11e9-935e-cf2ae71c63d0.png)

**Comment by madarche** [comment]
ACK

**Comment by madarche** [comment]
@A-312, convict@5.0.2 is in the process of being published, cf. #297
