### ISSUE TITLE
Should we add `source-array` like a default format ?

### ISSUE THREAD

**Issue by A-312** [mozilla/node-convict#303]
Hi,

Should i make an PR to add `source-array` (see the README) like a default type ?

https://github.com/mozilla/node-convict/blob/61e8b9b5b6c89ea905fe8cd962492342ea2b1100/lib/convict.js#L415-L441

**Comment by madarche** [comment]
It's better to strive of extensibility than for extensiveness cf. https://github.com/substack/blog/blob/master/node_aesthetic.markdown

So adding more formats than the basic ones is not desirable.

Please read https://github.com/mozilla/node-convict/issues/144#issuecomment-215178291 and tell if it convinces you.

**Comment by A-312** [comment]
I think, i can make a module and update the documentation about `source-array`. It is the same thing

**Comment by madarche** [comment]
@A-312 That would be great! I think this is the way to go.

And we could use keywords like `convict-plugin`, `convict-plugin-type`.

**Comment by A-312** [comment]
like `convict-source-array` ? I don't know how i can call this module

**Comment by madarche** [comment]
It's needed to have standardized prefixes.

* `convict-plugin` could be the main prefix for everything related to convict plugins
* `convict-plugin-format` could be the prefix for every convict format plugin

So your plugin could be named `convict-plugin-format-source-array`. It's a bit long, but it's eloquent and follows a clear pattern that could be followed by others.

What do you think?

**Comment by A-312** [comment]
It is a long prefix, but if we look on Symfony, Symfony uses tag search on github & npm to find public bundles.

**Comment by A-312** [comment]
I wonder if formats with `validator` package should be exported in dependencies ?
