### ISSUE TITLE
Dead link in Contributing.md

### ISSUE THREAD

**Issue by BourgoisMickael** [mozilla/node-convict#308]
The Node aesthetic (https://substack.net/node_aesthetic) link returns a `Page not found`.
Maybe you could use this one instead: https://github.com/substack/blog/blob/master/node_aesthetic.markdown
Or maybe you could explain what it is in case the other link dies too

**Comment by A-312** [comment]
@madarche this is issue is done

**Comment by BourgoisMickael** [comment]
Closed by #310
