### ISSUE TITLE
Current value not printed on error when the type is different

### ISSUE THREAD

**Issue by BourgoisMickael** [mozilla/node-convict#309]
For the format `port` and `nat` if the value is not an integer, the faulty value is not appended to the error message.

Example of normal behavior: 
```js
const convict = require('convict')

const config = convict({
  port: {
    format: 'port',
    default: -1
  }
})

config.validate({ allowed: 'strict' })
```
The output is:
```
Error: port: ports must be within range 0 - 65535: value was -1
```

However if I put a string instead:
```js
const convict = require('convict')

const config = convict({
  port: {
    format: 'port',
    default: 'hello world'
  }
})

config.validate({ allowed: 'strict' })
```
The output is:
```
Error: port: ports must be within range 0 - 65535
```
But it should be:
```
Error: port: ports must be within range 0 - 65535: value was "hello world"
```

**Comment by A-312** [comment]
[e.value](https://github.com/mozilla/node-convict/blob/a256dc7a6d072f9090c6b78b6fe48c6ec59e8fcd/lib/convict.js#L655) returns NaN when port is a string because coerce function convert value with [parseInt](https://github.com/mozilla/node-convict/blob/master/lib/convict.js#L419).

**Comment by BourgoisMickael** [comment]
Ok I understand, and I guess it adds to much complexity to keep the value from the input before it is coerced and print it in the error message. I close the issue
