### ISSUE TITLE
is convict.addParser(...require('json5')) really necesary?

### ISSUE THREAD

**Issue by opensas** [mozilla/node-convict#343]
I have a json config file with comments, single quotes and trailing commans, and if I comment the following lines:

```
// import json5 from 'json5'
// convict.addParser({ extension: 'json', parse: json5.parse });
```

everything works ok anyway

If it's no longer ncesary (which si good!!!) docs should be updated: https://github.com/mozilla/node-convict#allow-comments-in-json-files

Am I right?

**Comment by A-312** [comment]
@opensas I made this change because some user (like me) use YAML without JSON5.

Master is 6.0.0 : https://github.com/mozilla/node-convict/blob/master/CHANGELOG.md#600---2019-xx-xx

Npm is 5.2.0 (and support by default json5).

**Comment by opensas** [comment]
ok, then I´ll leave in commented waiting for 6.0 version. Is it the only change in 6.0? Any estimate date for publishing it?

**Comment by vladikoff** [comment]
We can work on the 6.0 release, you can also just install from github via a git sha for now

**Comment by A-312** [comment]
> ok, then I´ll leave it commented waiting for 6.0 version. Is it the only change in 6.0? Any estimate date for publishing it?

Commented or not that don't make a big change. When you use addParser, you add a key "json" in parsers_registry object.

loadFile : 
https://github.com/mozilla/node-convict/blob/be350a7ded016543b3eea16953be1f81c4bf34be/lib/convict.js#L449

addParser : 
https://github.com/mozilla/node-convict/blob/be350a7ded016543b3eea16953be1f81c4bf34be/lib/convict.js#L766

**Comment by madarche** [comment]
Thanks @A-312 for answering. We all want to have convict 6.0 released ASAP.
