### ISSUE TITLE
[Snyk] Prototype Pollution Affecting yargs-parser package

### ISSUE THREAD

**Issue by cyrille-arundo** [mozilla/node-convict#360]
`convict@5.2.0` requires `yargs-parser@13.0.0` (pinned version)
https://github.com/mozilla/node-convict/blob/68429a16c607750882dad721baa91fa4d7f3a2ee/package.json#L8

[Snyk](https://snyk.io/) reports the following **Medium Security** error:

> Prototype Pollution
> Affecting yargs-parser package, versions <13.1.2 || >=14.0.0 <15.0.1 || >=16.0.0 <18.1.1

See https://snyk.io/vuln/SNYK-JS-YARGSPARSER-560381

**Comment by mfechner** [comment]
Is there a new version of convict planned that includes this security fix?

**Comment by madarche** [comment]
@mfechner definitely **Yes**! And security is important to us. But it's hard to find the time to finalize the new version of convict. I'm the first to regret it 😭

On the projects I maintain, simply removing the  `package-lock.json` file and the `node_modules` directory and doing a new `npm install` reinstalls a whole new set of dependencies which `npm audit` doesn't report as having any vulnerability. But I know *npm audit* and *Snyk* don't report exactly the same vulnerabilities.

We'll do as fast as we can.
