### ISSUE TITLE
convict-format packages not found on npm or yarn

### ISSUE THREAD

**Issue by QmarkC** [mozilla/node-convict#362]
The convict-format-with-validator and convict-format-with-moment packages are not found on npm or yarn.

https://yarnpkg.com/?q=convict-format-with-validator
https://www.npmjs.com/search?q=convict-format-with-validator
https://yarnpkg.com/?q=convict-format-with-moment
https://www.npmjs.com/search?q=convict-format-with-moment

**Comment by madarche** [comment]
convict@6 is not published yet :-(

**Comment by QmarkC** [comment]
Ok thanks. I am just getting started with convict and didn't realize those were part of the upcoming release. It might be helpful to add a note to the README files. Listing convict@6 in the peerDependencies would have also helped me catch this as well.
