### ISSUE TITLE
`getSchema()` broken in 6.0.0

### ISSUE THREAD

**Issue by MrBartusek** [mozilla/node-convict#376]
`getSchema` works differently now and [migration guide](https://github.com/mozilla/node-convict/blob/master/packages/convict/MIGRATING_FROM_CONVICT_5_TO_6.md) not that;

that code worked before 6.0:
```ts
if(!Config.data.getSchema().properties[key]) throw new Error(`'${key}' value don't exist in config schema while something tried to access it`);
```

now it must be:
```ts
if(!Config.data.getSchema()._cvtProperties[key]) throw new Error(`'${key}' value don't exist in config schema while something tried to access it`);
```

I don't think that's intended

**Comment by A-312** [comment]
`properties` was replaced by `_cvtProperties` to allow the word `properties` in your config. ;) In 6.0, `properties` was a private word.

**Comment by A-312** [comment]
Also 6.0.0 is partial version of wanted changes, because [the next version >=7.0](https://github.com/mozilla/node-convict/pull/357) should be have different behavior with getSchema() to do something like that: `!Config.data.getSchema()[key]`

**Comment by madarche** [comment]
Thanks @A-312!
