### ISSUE TITLE
6.0.1 version of Convict-format-with-validator package is using vulnerable version of validator module

### ISSUE THREAD

**Issue by mallikde-kore** [mozilla/node-convict#394]
Validator package versions before 13.6.0 are vulnerable to ReDOS (Regular Expression Denial of Service) via isEmail and isHSL. The vulnerability can happen when checking if the crafted string is an email.

Validator has fixed this in their latest version 13.6.0.

Could see this validator module has been upgraded to 13.6.0 in version 6.2.0 of Convict-format-with-validator. Could you please release this to npm.

**Comment by madarche** [comment]
Hello. The ticket #393 is for taking care of the release to npm.
