### ISSUE TITLE
Support using convict in a (browserify-based) browser context

### ISSUE THREAD

**Issue by ronjouch** [mozilla/node-convict#47]
Hi.

I'm trying to use your package in a browserify setup, but because `conf.loadFile('some.json')` calls various `fs` methods (`fs.statSync`, `fs.readdirSync`), it fails in the browser.

→ Is it something that sounds feasible with convict (or maybe with a browserify transform?), or do you suggest going for another package / custom solution?

Thanks for the help, and sorry for posting this as an issue, it's more of a question to which "we do not and will not support that" can be a fine answer.

**Comment by DamonGant** [comment]
There are a few things preventing this from being browserified:

* `dep` uses v8-specific `Error` functions. Works on Chrome. Doesn't anywhere else.
* `load` now uses `fstat`, which isn't implemented by brfs
