### ISSUE TITLE
Update changelog

### ISSUE THREAD

**Issue by pdehaan** [mozilla/node-convict#56]
It looks like the [ChangeLog](https://github.com/mozilla/node-convict/blob/master/ChangeLog) file hasn't been updated since 0.4.1 and the [Releases](https://github.com/mozilla/node-convict/releases) page hasn't been updated since 0.5.1.

It makes it a bit tricky to see what's changed between versions unless you compare 2 different SHAs.

Not sure if there is an easy Git command that you can use to generate a passable looking changelog so you don't need to do it manually, or bring in Grunt or something.

**Comment by madarche** [comment]
@pdehaan I agree that a fully documented ChangeLog is needed. It's not that hard to do it from Git history. I can do it or make some students of mine work on it. So I take the lead on this action. As for the Releases page, yes it's missing some tags :-( but only the owners of this repository can manage it.
