### ISSUE TITLE
Use shrinkwrap to lock module dependencies

### ISSUE THREAD

**Issue by pdehaan** [mozilla/node-convict#63]
We may want to use something like [shrinkwrap](https://docs.npmjs.com/cli/shrinkwrap) (`$ npm shrinkwrap --dev`) to lock down the dependency versions. Plus, it'd make it easier to integrate tooling with tools like [**nsp**](https://www.npmjs.com/package/nsp) which checks for known vulnerabilities against the https://nodesecurity.io/advisories database.

**Cons:** we'd need to rerun `npm shrinkwrap --dev` each time we change the module versions in package.json and commit the npm-shrinkrwap.json file into the repo.

---

Current `nsp` output:
```sh
$ npm shrinkwrap --dev
wrote npm-shrinkwrap.json

$ nsp shrinkwrap
No vulnerable modules found
```

**Comment by madarche** [comment]
npm@3 automatically updates the npm-shrinkwrap.json when present cf. http://blog.npmjs.org/post/113882628280/npm-weekly-9

So I would say we can safely and easily do what you propose once npm@3 is included in current Node.js.
