### ISSUE TITLE
Disallowing undeclared properties in configuration files

### ISSUE THREAD

**Issue by umar-muneer** [mozilla/node-convict#65]
So i compared the configuration schema for convict to a normal database schema. A table can only have columns that are declared in the schema and no additional ones. 

I think convict should have a strict validation mode, in which only those properties should be allowed to be declared in different config files(staging,dev,prod) which are declared in the schema.

I have added a pull request doing just that. @zaach, Please review.

**Comment by madarche** [comment]
Merging #64 has fixed this issue. 

@zaach could you close this  please?

**Comment by madarche** [comment]
@zaach could you close this one please?
