### ISSUE TITLE
Documentation using deprecated `validator.check`

### ISSUE THREAD

**Issue by mmerkes** [mozilla/node-convict#73]
In the validation section of the README.md, it uses `validator.check`, which disappeared from validator a long time ago. I've created a PR to remove that and show a valid example of a custom format function.

**Comment by mmerkes** [comment]
Also, I would like to flesh out the example a bit to include most/all of the features in it.

**Comment by madarche** [comment]
You're right!

Still, you can close this issue, and the work can be done in #74. No need to have two open "tickets" for the same thing (Pull Requests are just special Issues with solutions :-) ).

As for providing better examples, you are most welcome. But I'd suggest to do one thing at a time: let's fix the deprecated use of `validator.check` and then let's provide improved examples.

**Comment by mmerkes** [comment]
Sounds good. Whatever flow is preferred. I opened up the issue and PR, as many projects prefer having issues and a PR to close them. I'll update the PR tonight, and I will create a new PR when I flesh out the examples.

**Comment by madarche** [comment]
Thanks! And, yes, having separated issues and PR might be handy for (bigger) projects where different concurrent solutions (PRs) for a same problem (issue) are proposed.

**Comment by mmerkes** [comment]
Ah, that's a good argument to differentiate between the purpose of the two flows.
