### ISSUE TITLE
Nested Config in schema

### ISSUE THREAD

**Issue by ksmithut** [mozilla/node-convict#78]
I didn't see this anywhere in the documentation, but is there a way to have nested config variables in the config schema definition? For example:

```
var config = require('convict')({
  loggly: {
    token: {
      doc: '',
      format: String,
      env: 'LOGGLY_TOKEN'
    },
    subdomain: {
      doc: '',
      format: String,
      env: 'LOGGLY_SUBDOMAIN'
    }
  }
});
```

edit: Or is there another way to go about this completely? My only requirement would be to not store the information in a file. I know I can do nested config there, but I want the schema functionality to get the config variables from environment variables.

**Comment by madarche** [comment]
Yes, nested configuration variables are supported, and there is one such example in file [test/validation-tests.js](https://github.com/mozilla/node-convict/blob/master/test/validation-tests.js#L16).

And yes, this should be documented.

Cheers,

**Comment by ksmithut** [comment]
That works perfectly :) Thank you
