### ISSUE TITLE
Update package.json license format

### ISSUE THREAD

**Issue by myndzi** [mozilla/node-convict#81]
Convict's package.json is giving me trouble with license validation. It appears to use a deprecated license format; please consider updating it to something more recent:

https://docs.npmjs.com/files/package.json#license

**Comment by madarche** [comment]
Please provide a PR with the fix! It will be much welcome. Thanks!

**Comment by myndzi** [comment]
It's such a trivial change that it's a bit of a time waste for me to go through all the hoops to do that... but you got back to me so fast, here you go: https://github.com/mozilla/node-convict/pull/82

**Comment by madarche** [comment]
@zaach could you merge this PR please? Thanks!

**Comment by pdehaan** [comment]
I think this was fixed by https://github.com/mozilla/node-convict/commit/bfa4089310bf7b3cf9b3b23c79e1b852ce6df547

**Comment by myndzi** [comment]
Yeah, I sent the PR and it was accepted, but the issue didn't get closed. Sorry.

**Comment by myndzi** [comment]
https://github.com/mozilla/node-convict/pull/82
