### ISSUE TITLE
Incomprehensible errors when missing default property

### ISSUE THREAD

**Issue by ekaradon** [mozilla/node-convict#88]
When using strict mode, I get troubles with unknowns parameters. I am thinking that it may be because I am using a nested tree and I am completing it with parameters from a json file. 

```
        throw new Error(errBuf);
              ^
Error: configuration param '0' not declared in the schema
configuration param '1' not declared in the schema
configuration param '2' not declared in the schema
configuration param '3' not declared in the schema
...
```

This is while I am using ES6 notation. 

When I try with a really simple test on ES5, I cannot get farther than:

```
  Object.keys(instance).reduce(function(previousErrors, name) {
         ^
TypeError: Object.keys called on non-object
    at Function.keys (native)
    at validate ([...]/test/node_modules/convict/lib/convict.js:64:10)
```

Here the sample in ES5:
**config.js**

``` javascript
var convict = require('convict');

var schema = {
    env: {
        doc: 'The application environment.',
        format: ['production', 'development', 'test'],
        default: 'development',
        env: 'NODE_ENV'
    },
    first: {
        second: {
            third: {
                doc: 'Rest API backend URL',
                format: 'url'
            }
        }
    }
};

var conf = convict(schema);
var env = conf.get('env');
conf.loadFile(__dirname + '/config/' + env + '.json');
conf.validate({strict:true});
```

**developement.json**

``` json
{
  "first": {
    "second": {
      "third": "http://foo.com/"
    }
  }
}
```

Notice that w/ or w/0 the strict mode enabled, it does not work with a nested tree in ES5. In ES6 it does work only with strict mode disabled. 

I do not think having forgotten something because it does work while I am not configuring values for nested parameters.

**Comment by shamil** [comment]
I guess you need to specify a `default` value, in the `first.second.third` definition

**Comment by fkm** [comment]
Or disable strict validation.

**Comment by madarche** [comment]
This problem arises when no default property is set for a field. We should better check schema validity on schema creation.

**Comment by A-312** [comment]
We got the same thing when we use the filepath instead an object with .load().

**Comment by A-312** [comment]
> I guess you need to specify a `default` value, in the `first.second.third` definition

Right because convict understands : 

```js
{
  "env": {
    "doc": "The application environment.",
    "format": [
      "production",
      "development",
      "test"
    ],
    "default": "development",
    "env": "NODE_ENV"
  },
  "first": {
    "second": {
      "third": {
        "doc": {
          "default": "Rest API backend URL",
          "format": "String"
        },
        "format": {
          "default": "url",
          "format": "String"
        }
      }
    }
  }
}
```

**Comment by A-312** [comment]
Should be closed because not reproductible : 
I try `conf.validate({strict:true});` and `conf.validate();`.

```js
Error: configuration param 'first.second.third.doc' missing from config, did you override its parent?
configuration param 'first.second.third.format' missing from config, did you override its parent?
```

```js
const schema = {
    env: {
        doc: 'The application environment.',
        format: ['production', 'development', 'test'],
        default: 'development',
        env: 'NODE_ENV'
    },
    first: {
        second: {
            third: {
                doc: 'Rest API backend URL',
                format: 'url'
            }
        }
    }
};

const conf = convict(schema);
conf.load({
  "first": {
    "second": {
      "third": "http://foo.com/"
    }
  }
});
conf.validate({strict:true});
```

Also I tried with : 

```js
const schema = {
  "env": {
    "doc": "The application environment.",
    "format": [
      "production",
      "development",
      "test"
    ],
    "default": "development",
    "env": "NODE_ENV"
  },
  "first": {
    "second": {
      "third": {
        "doc": {
          "default": "Rest API backend URL",
          "format": "String"
        },
        "format": {
          "default": "url",
          "format": "String"
        }
      }
    }
  }
};
```

**Comment by ekaradon** [comment]
The error you give is a bit weird. Does it mean you have to copy/paste the  documentation when overriding your configuration?
I - personally - don't use this library anymore. I can close if you ask or you can just go with it and close it.

**Comment by A-312** [comment]
We can improve the message like this:

`did you override `doc` property parent?`

or

`configuration param 'first.second.third.format' missing from config, did you override its parent? because: first.second.third` is a string

**Comment by ekaradon** [comment]
From what I can remember, these fields (format & doc) are intended to help the developer to understand what values can be used. Not something he should override. So I would expect to have no issue at all with your first example.

**Comment by A-312** [comment]
> From what I can remember, these fields (format & doc) are intended to help the developer to understand what values can be used. Not something he should override. So I would expect to have no issue at all with your first example.

You didn't write that you wanted to do. You had to write:

```js
third: {
  doc: 'Rest API backend URL',
  format: 'url',
  default: undefined
}
```

`dedault` is required, `doc` and `format` are optionnal and they are not a reserved word in config schema.

**Comment by ekaradon** [comment]
Ok, I am closing this.

**Comment by A-312** [comment]
I find a solution (a new error message): 

```
Validate failed because wrong value(s):
  - config parameter "first.second.third.four" missing from config, did you override its parent? Because "first.second.third" is null.
```

https://github.com/mozilla/node-convict/pull/357/commits/dc8fdcdd4b9986e30c8b7ff18b41164882e175c7
